M48
; DRILL file {KiCad 7.0.8+1} date dom 19 nov 2023 13:01:44
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-19T13:01:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1122
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1378
%
G90
G05
T1
X3.8766Y-1.9031
X3.8766Y-2.2969
X3.975Y-1.9031
X3.975Y-2.2969
X4.1719Y-2.1
T2
X7.6Y-1.9
X7.6Y-5.4
T3
X6.0441Y-1.9
T0
M30
